version: "3"

services:
  db:
    image: postgres
    networks:
      - shopnet
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: shop
      POSTGRES_PASSWORD: ue3um2yRJA
    
  app:
    build: .
    image: shop:latest
    environment:
      FLASK_ENV: config.ProductionConfig
      SQLALCHEMY_DATABASE_URI: "postgresql://admin:ue3um2yRJA@db:5432/shop"    
    ports:
        - "8081:8080"


networks:
  shopnet:
