version: "3"

services:
  db:
    image: postgres
    networks:
      - shopnet
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: shop
      POSTGRES_PASSWORD: ue3um2yRJA

  shop:
    build:
      context: .
      dockerfile: shop/Dockerfile
    environment:
      FLASK_ENV: config.ProductionConfig
      SQLALCHEMY_DATABASE_URI: "postgresql://admin:ue3um2yRJA@db:5432/shop"
    ports:
      - "8081:8080"

  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    ports:
      - "5000:8080"

networks:
  shopnet:
